python:
    - 3.10
    - 3.11
    - 3.12
    - 3.13

cuda_version:
    - 12.0
    - 12.1
    - 12.2
    - 12.3
    - 12.4
    - 12.5
    - 12.6

hdf5:
    - 1.10
    - 1.12
    - 1.14

# Define valid combinations
zip_keys:
  - python
  - hdf5

# Specify valid combinations
zip_values:
  - [3.10, 1.12]
  - [3.10, 1.14]
  - [3.11, 1.12]
  - [3.11, 1.14]
  - [3.12, 1.12]
  - [3.12, 1.14]
  - [3.13, 1.12]
  - [3.13, 1.14]
